
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: imed
  password: 123456

development:
  <<: *default
  database: auth_db

test:
  <<: *default
  database: auth_db_test

production:
  <<: *default
  database: auth_db_production
  username: auth_prod
  password: <%= ENV['AUTH_PROD_DATABASE_PASSWORD'] %>
